### ISSUE TITLE
the article is down

### ISSUE THREAD

**Issue by loneicewolf** [landhb/HideProcess#16]
# Hi!

### as the title suggests

![image](https://user-images.githubusercontent.com/68499986/221652419-1906fa0e-dbb9-446a-8e5f-e2447f070af1.png)

### Results in 

![image](https://user-images.githubusercontent.com/68499986/221652465-050e7f73-d180-4500-9c1f-75738080edfc.png)

Which makes me make this issue; can you update or include the article in file-mode ? (paper -> pdf) or something?

## Wishes from Sweden!

`over n out. //Will.`

**Comment by landhb** [comment]
@loneicewolf The articles are currently down, but they are archived on archive.org.

https://web.archive.org/web/20210512005244/https://blog.landhb.dev/posts/v9eRa/a+basic+windows+dkom+rootkit

**Comment by loneicewolf** [comment]
> @loneicewolf The articles are currently down, but they are archived on archive.org.
> 
> https://web.archive.org/web/20210512005244/https://blog.landhb.dev/posts/v9eRa/a+basic+windows+dkom+rootkit


**great**! Maybe update the readme would be a great Idea, so others know about it :)
