### ISSUE TITLE
lost files

### ISSUE THREAD

**Issue by lzcykevin** [landhb/HideProcess#4]
I use visual studio 2017 to build this project, but has a error that is lost ndis_debug.h and tcphook.h

**Comment by landhb** [comment]
Thanks, forgot to remove a few things, my local working directory is a little different than the repo.

Fixed in latest commit fdbd0dc114587bc9a590bdc3eb766d052f7d0cab

**Comment by lzcykevin** [comment]
also has a error that is in recievepackets.c can not find ndis_sniff.h

**Comment by landhb** [comment]
Fixed in d09eb89e1872258e49b67ae4fb75103c9e1c48f3

**Comment by lzcykevin** [comment]
I test it, that's ok, thanks
